repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  # Prevent committing to the master branch
  - id: no-commit-to-branch
    args: [--branch, master]
  # Format yaml files
  - id: check-yaml
  # Fix end-of-file issues
  - id: end-of-file-fixer
  # Fix trailing whitespace
  - id: trailing-whitespace
  # Prevent debug statements
  - id: debug-statements
  - id: fix-encoding-pragma
  - id: mixed-line-ending
# Code formatting
- repo: https://github.com/ambv/black
  rev: 25.1.0
  hooks:
  - id: black
    exclude: tests
# Further linting (e.g. module imported but not used)
- repo: https://github.com/PyCQA/flake8
  rev: 7.2.0
  hooks:
  - id: flake8
    exclude: ^(tests/|scripts/|docs/)
- repo: local
  hooks:
#    - id: nbstripout
#      name: nbstripout with keep-output
#      entry: |
#        python -m nbstripout --keep-output $@
#      language: system
#      files: \.ipynb$
    - id: poetry-export
      name: poetry-export
      entry: |
        bash -c poetry export -f requirements.txt --output requirements.txt --with dev --with test --with docs -E clipboard -E download -E express -E gel
      language: system
      files: ^(pyproject\.toml|poetry\.lock)$
