default_stages: [pre-commit]
exclude: ^(tests/)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Format yaml files
      - id: check-yaml
        # Ignore conda build meta.yaml files
        exclude: ^scripts/conda-build/meta.*\.yaml$
      # Fix end-of-file issues
      - id: end-of-file-fixer
      # Fix trailing whitespace
      - id: trailing-whitespace
      # Prevent debug statements
      - id: debug-statements
      - id: fix-encoding-pragma
      - id: mixed-line-ending

  # Code formatting
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black
        files: ^src/

  # Further linting (e.g. module imported but not used)
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]

  # Remove metadata from jupyter notebooks. This will always be triggered when you commit a change in a notebook.
  - repo: local
    hooks:
      - id: nbstripout
        name: nbstripout with keep-output
        entry: |
          python -m nbstripout --keep-output $@
        language: system
        files: \.ipynb$
        exclude: tests/
