default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Format yaml files
      - id: check-yaml
        # Ignore conda build meta.yaml files
        exclude: ^scripts/conda-build/meta.*\.yaml$
      # Fix end-of-file issues
      - id: end-of-file-fixer
      # Fix trailing whitespace
      - id: trailing-whitespace
      # Prevent debug statements
      - id: debug-statements
      #- id: fix-encoding-pragma
      - id: mixed-line-ending

# This was recommended but seems very opinionated.
#- repo: https://github.com/asottile/pyupgrade
#  rev: v3.20.0
#  hooks:
#    - id: pyupgrade
#      args: [--py310-plus]

  # Linting and formatting with ruff (replaces black + flake8)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Remove metadata from jupyter notebooks. This will always be triggered when you commit a change in a notebook.
  - repo: local
    hooks:
      - id: nbstripout
        name: nbstripout with keep-output
        entry: |
          python -m nbstripout --keep-output $@
        language: system
        files: \.ipynb$
        exclude: tests/
