[pytest]
filterwarnings =
    ignore:Partial overlaps can return wrong products.*:UserWarning
    ignore:Some recombination products were discarded because they had off-target cuts.*:UserWarning
    ignore:The user_assembly_design function is experimental and may change in future versions.*:FutureWarning
    ignore:Increasing length of locus line to allow long name.*:
    ignore:Feature qualifier key.*:Bio.BiopythonWarning
    ignore:Truncated LOCUS line found - is this correct\?.*:Bio.BiopythonWarning
    ignore:LOCUS line is wrongly formatted, we used a more permissive parser.*:UserWarning
    ignore:The primer_screen module is experimental.*:FutureWarning

markers =
    mpl_image_compare
