# -*- coding: utf-8 -*-
"""Restriction digestion followed by ligation, including Golden Gate.

The fragments are cut and joined in one step, so the join rule depends on the
enzymes supplied at the call. Golden Gate is this same reaction run with a
Type-IIS enzyme, and is exposed under its own name.
"""

from __future__ import annotations

import warnings

from pydna.assembly import restriction_ligation_overlap
from pydna.assembly import (
    partially_digested_seqs_in_restriction_ligation_assembly as _partially_digested,
)
from pydna.methods._engine import Method, Shape
from pydna.methods._registry import register
from pydna.opencloning_models import RestrictionAndLigationSource
from pydna.utils import deduplicate

__all__ = ["restriction_ligation_assembly", "golden_gate_assembly"]


def _algorithm(params: dict):
    """Cut with the given enzymes and join the compatible ends."""
    enzymes = params["enzymes"]
    allow_blunt = params.get("allow_blunt", True)

    def algorithm_fn(x, y, _l):
        # By default, we allow blunt ends
        return restriction_ligation_overlap(x, y, enzymes, False, allow_blunt)

    return algorithm_fn


def _drop_partially_digested(products, inputs, params):
    """Remove products that required a partial digestion, warning about them."""
    filtered = []
    partially_seqs = []
    for p in products:
        these_seqs = _partially_digested(p)
        if len(these_seqs) == 0:
            filtered.append(p)
        else:
            partially_seqs.extend(these_seqs)
    # Dedupe by id:
    partially_seqs = deduplicate(partially_seqs, hashable=False)
    if len(partially_seqs) > 0:
        formatted_seqs = ", ".join(
            [f"Seq {seq.name} (id: {seq.id})" for seq in partially_seqs]
        )
        warnings.warn(
            f"{len(partially_seqs)} partially digested products were filtered out: {formatted_seqs}",
            stacklevel=2,
            category=UserWarning,
        )
    return filtered


restriction_ligation_assembly = register(
    Method(
        name="restriction_ligation",
        doc="""Returns the products for restriction ligation assembly:

    - Finds cutsites in the fragments
    - Finds all products that could be assembled by ligating the fragments based on those cutsites
    - Will NOT return products that combine an existing end with an end generated by the same enzyme (see example below)

    Parameters
    ----------
    frags : list[Dseqrecord]
        List of DNA fragments to assemble
    enzymes : list[AbstractCut]
        List of restriction enzymes to use
    allow_blunt : bool, optional
        If True, allow blunt end ligations, by default True
    circular_only : bool, optional
        If True, only return circular assemblies, by default False

    Returns
    -------
    list[Dseqrecord]
        List of assembled DNA molecules

    Examples
    --------
    In the example below, we plan to assemble a plasmid from a backbone and an insert, using the EcoRI and SalI enzymes.
    Note how 2 circular products are returned, one contains the insert (``acgt``)
    and the desired part of the backbone (``cccccc``), the other contains the
    reversed insert (``tgga``) and the cut-out part of the backbone (``aaa``).

    >>> from pydna.methods import restriction_ligation_assembly
    >>> from pydna.core.dseqrecord import Dseqrecord
    >>> from Bio.Restriction import EcoRI, SalI
    >>> backbone = Dseqrecord("cccGAATTCaaaGTCGACccc", circular=True)
    >>> insert = Dseqrecord("ggGAATTCaggtGTCGACgg")
    >>> products = restriction_ligation_assembly([backbone, insert], [EcoRI, SalI], circular_only=True)
    >>> products[0].seq
    Dseq(o22)
    TCGACccccccGAATTCaggtG
    AGCTGggggggCTTAAGtccaC
    >>> products[1].seq
    Dseq(o19)
    AATTCaaaGTCGACacctG
    TTAAGtttCAGCTGtggaC

    Note that passing a pre-cut fragment also works.

    >>> restriction_products = insert.cut([EcoRI, SalI])
    >>> cut_insert = restriction_products[1]
    >>> restriction_ligation_assembly([backbone, cut_insert], [EcoRI, SalI], circular_only=True)
    [Dseqrecord(o22), Dseqrecord(o19)]

    It also works with a single fragment, for circularization:

    >>> seq = Dseqrecord("GAATTCaaaGAATTC")
    >>> products =restriction_ligation_assembly([seq], [EcoRI])
    >>> products[0].seq
    Dseq(o9)
    AATTCaaaG
    TTAAGtttC
        """,
        shape=Shape.ASSEMBLY,
        algorithm_factory=_algorithm,
        source=RestrictionAndLigationSource,
        limit=None,
        only_adjacent_edges=True,
        filter_products=_drop_partially_digested,
        source_fields=lambda inputs, params: {"restriction_enzymes": params["enzymes"]},
        positional=("frags", "enzymes", "allow_blunt", "circular_only"),
        summary="Cut fragments with restriction enzymes and ligate the "
        "compatible ends.",
    )
)

#: Golden Gate is restriction-ligation with a Type-IIS enzyme; the reaction, and
#: therefore the recorded provenance, is identical.
golden_gate_assembly = restriction_ligation_assembly
